---
- hosts: wordpress_nodes
  become: yes
  vars:
    project_name: wp_raf
    database_password: "SuperStrongPasssword"
    wordpress_url: https://wordpress.org/latest.tar.gz
  tasks:
    - name: "Install httpd server"
      yum:
        name: httpd
        state: latest
    - name: "Restart httpd service"
      service:
        name: httpd
        state: restarted
    - name: "install php module"
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - php
        - php-mysql
    - name: "install db server"
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - mariadb
        - mariadb-server
        - MySQL-python
    - name: "restart mariadb"
      service:
        name: mariadb
        state: restarted
    - name: "create directory for wordpress"
      file:
        path: "/var/www/{{project_name}}"
        state: directory
    - name: "download and install WordPress"
      unarchive:
        src: "{{wordpress_url}}"
        dest: "/var/www/{{project_name}}"
        remote_src: yes
        extra_opts: [--strip-components=1]
    - name: "create wordpress database"
      mysql_db:
        name: "{{project_name}}"
        state: present
    - name: "create wordpress database user"
      mysql_user:
        name: "db_{{project_name}}"
        password: "{{database_password}}"
        priv: '*.*:ALL'
        state: present
    - name: "configure vhosts"
      template:
        src: "./templates/vhosts.conf"
        dest: /etc/httpd/conf.d/wp.conf
    - name: "configure wordpress"
      template:
        src: ./templates/wp-config.php
        dest: "/var/www/{{project_name}}/wp-config.php"
    - name: "Reload httpd"
      service:
        name: httpd
        state: restarted